name: DashLord publish Airtable

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["DashLord scans"]
    types:
      - completed

# allow only one concurrent publish action
concurrency:
  cancel-in-progress: true
  group: scans

jobs:
  init:
    runs-on: ubuntu-latest
    name: Prepare
    outputs:
      json: ${{ steps.init.outputs.json }}
    steps:
      - uses: actions/checkout@v2
      - id: init
        uses: "DISIC/dashlord-observatoire/actions/airtable-procedures-urls@main"
        with:
          airtable_api_key: ${{ secrets.AIRTABLE_API_KEY }}
          airtable_base_id: ${{ secrets.AIRTABLE_BASE_ID }}
          airtable_procedures_table_name: ${{ secrets.AIRTABLE_TABLE_NAME }}
          airtable_editions_table_name: ${{ secrets.AIRTABLE_EDITIONS_TABLE_NAME }}
          output: airtable-procedures_urls.json

  publish:
    runs-on: ubuntu-latest
    name: Publish
    needs: init
    continue-on-error: false
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        sites: ${{ fromJson(needs.init.outputs.json) }}
    steps:
      - uses: actions/checkout@v2

      - name: Airtable insert data
        continue-on-error: true
        uses: "DISIC/dashlord-observatoire/actions/airtable-insert-data@main"
        with:
          id: ${{ matrix.sites.id }}
          airtable_api_key: ${{ secrets.AIRTABLE_API_KEY }}
          airtable_base_id: ${{ secrets.AIRTABLE_BASE_ID }}
          airtable_table_name: ${{ secrets.AIRTABLE_TABLE_NAME }}
